### ISSUE TITLE
Cannot show the blue line 

### ISSUE THREAD

**Issue by lannyho** [aws-samples/aws-cloudwatch-snapshot-graphs-alert-context#1]
Hi, I tried to follow your instruction and cannot show the blue line
![fault](https://user-images.githubusercontent.com/745623/46584566-87ae0000-ca97-11e8-9320-5658005cbe1a.png)

beside, is there any way to run on different region? For example, Tokyo...

**Comment by wisemanIV** [comment]
Sanity check the metric by searching for it in the CloudWatch console and adding it to a chart. If you can't see any line / data in CloudWatch then your EC2 is not emitting data. If it looks ok in CloudWatch check the alarm is referencing the same instance Id and check the scale on the Y axis. You can run in any region as long as the metric, alarm and Lambda are in the same region.

**Comment by lannyho** [comment]
Hi WisemanIV,

   I checked that is the same instance Id, but I don't understand what's the meaning of scale on the Y axis, In my understanding of your code emailer.js, it uses this function getYMax(s) to return the datapoint of Y axis. Beside, I tried to run the lambda on Singapore region, it shows the region error, after I tried to add a environment variable AWS_REGION on lambda, it shows error.

**Comment by wisemanIV** [comment]
Do you see the metric in the CloudWatch console? What does it look like when you add it to a graph in the console? Singapore region should be ok. What error are you getting? The region parameter is provided by Lambda based on the region the function is executing in, you don't need to add it as an environment variable.

**Comment by lannyho** [comment]
Hi, please check 
![region fault](https://user-images.githubusercontent.com/745623/46710837-4c205b00-cc7c-11e8-83bf-a3b58bd6b834.png)

**Comment by lannyho** [comment]
Hi, I tried another way to run lambda function on Virginia region, it can sends email to me, but this graph still no metric / blue line...

![fault-virginia-cw-metric-01](https://user-images.githubusercontent.com/745623/46711472-0e710180-cc7f-11e8-88c5-e072a1a12160.png)


![fault-virginia-cw-metric-02](https://user-images.githubusercontent.com/745623/46711477-13ce4c00-cc7f-11e8-921f-516b4d601cc2.png)


![fault-email](https://user-images.githubusercontent.com/745623/46711481-18930000-cc7f-11e8-83d4-917a18d9aabe.png)


Our environment 
EC2  (Singapore region)
Cloudwatch  (Singapore region)
Cloudwatch alarm  (Singapore region)
SNS  (Singapore region)
Lambda (Virginia region)

**Comment by wisemanIV** [comment]
Hi, sorry the Simple Email Service (SES) has limited regional availability. See the service availability matrix for a list of regions where SES is available - https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/. I'll update the documentation to reflect this limitation. If you need to send emails from a region that is not supported by SES you will have to use a different email service. 

As for why the line is not rendering, I'm guessing it is because your Lambda is in Virginia but your metric is in Singapore region. The Lambda will call the CloudWatch API in Virginia and the metric will not be found in that region. Check the Lambda logs for errors.

**Comment by lannyho** [comment]
Hi, thanks your reply, may I give a little suggestion for this apps, is it possible to using this method to send email without concern region, for example

1. Create a IAM user, attached policy to access SES function, and create a new accesskey for access SES
2. Create a credentials.js to access SES and send email, like this

`var aws = require('aws-sdk');`
`var ses = new aws.SES({apiVersion: '2010-12-01',`
`                        accessKeyId: '<accesskeyID>',`
`                        secretAccesskey: '<secretAccesskey>',`
`                        region: 'us-east-1' });`

**Comment by lannyho** [comment]
I modified your code and it works for me
![cw-enhance01](https://user-images.githubusercontent.com/745623/46916616-993f5c80-cfef-11e8-9779-51abeb5f8890.png)
![cw-enhance02](https://user-images.githubusercontent.com/745623/46916618-9cd2e380-cfef-11e8-9ec9-115a1a6e7c46.png)
![cw-enhance03](https://user-images.githubusercontent.com/745623/46916621-a3615b00-cfef-11e8-9332-f1d6b94ba27f.png)
![cw-enhance04](https://user-images.githubusercontent.com/745623/46916622-a5c3b500-cfef-11e8-8dce-3c35b81d699a.png)

**Comment by wisemanIV** [comment]
Thanks for this. I will test the solution and look to incorporate into the next version.
